### ISSUE TITLE
Bind volumes not currently supported

### ISSUE THREAD

**Issue by xenoscopic** [mutagen-io/docker-desktop-extension-issues#1]
Docker allows for the creation of bind mounts directly into volumes, for example via the following Compose configuration:

```
volumes:
  boundvolume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/some/path"
```

or via the corresponding `docker volume create` command.

At the moment, the extension doesn't enable caching for these types of binds (meaning they continue to fall back to gRPC-FUSE or Virtiofs).

While these configurations aren't commonly used, it would be worth supporting them.  Compose just fixed their support for this in v2.6.1, which is an indication that at least someone is using this functionality.
