### ISSUE TITLE
PHP Container not listed in "Used by" pane

### ISSUE THREAD

**Issue by aprat84** [mutagen-io/docker-desktop-extension-issues#10]
Hi.

I have a docker-compose.yml with some services (nginx, php, mysql, mongodb, ...).

Some services have named volumes (mysql, mongodb)
Some services have bind mounts for source code (nginx, php) and for config files (nginx, php, mysql, ...)

I've created a cache for the whole repository directory, and when I restart the services, only 2 of these containers are shown in "Used by" pane.

The `docker-compose.yml` looks like this:

```yaml
version: '3'
services:
    nginx:
        image: 'nginx:mainline-alpine'
        ports:
            - '8500:80'
        volumes:
            - '.:/var/www/html'
            - './.docker/nginx/conf.d:/etc/nginx/conf.d'
            - './.docker/nginx/snippets:/etc/nginx/snippets'
        networks:
            - mynetwork
        depends_on:
            - php
    php:
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
            args:
                WWW_GROUP: '${WWW_GROUP}'
                WWW_USER: '${WWW_USER}'
        image: 'my/php-8.2-alpine:default'
        user: ${WWW_USER}:${WWW_GROUP}
        volumes:
            - '.:/var/www/html'
            - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php-custom.ini'
        networks:
            - mynetwork
        depends_on:
            - mysql
            - mongo
    mysql:
        image: 'mysql:8.0-oracle'
        ports:
            - '8501:3306'
        environment:
            # some env vars
        volumes:
            - 'mysql:/var/lib/mysql'
            - './.docker/mysql/init:/docker-entrypoint-initdb.d'
            - './.docker/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf'
        networks:
            - mynetwork
    mongo:
        image: 'mongo:5'
        ports:
            - '8506:27017'
        environment:
            # some env vars
        volumes:
            - 'mongo:/data/db'
            - './.docker/mongo/mongod.yaml:/etc/mongo/mongod.yaml'
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

volumes:
    mysql:
        driver: local
    mongo:
        driver: local

```

If I change the `php` service as following, then it appears, but then my app's obviously not working...

```yaml
    php:
        image: 'php:8.2-alpine'
        volumes:
            - '.:/var/www/html'
            - './.docker/php/php.ini:/usr/local/etc/php/conf.d/php-custom.ini'
        networks:
            - mynetwork
        depends_on:
            - mysql
            - mongo
```

Any thoughts?

Extension version: v0.17.3 (free)
Docker desktop version: 4.25.0
Platform: macOS 14.1 (arm)
